POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "adam_richard1234",
  "name": "Adam Richard1234",
  "password": "1234567",
  "gender": "male",
  "location": "Detroit"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "adam_richard12",
  "password": "richsas"
}

#######

PUT http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "adam_richard12",
  "oldPassword": "richsas123",
  "newPassword": "richsas1234567"
 
}